### ISSUE TITLE
Form not displayed

### ISSUE THREAD

**Issue by greergan** [pencilblue/contact-pencilblue#5]
Hello,

I have have installed this plugin and followed the directions, however the form is not displayed. I am using the 0.4.1 release.

**Comment by brianhyder** [comment]
I attempted to replicate using the master branch of pencilblue.  I installed the contact-pencilblue plugin.  Then modified the template for the sample plugin to include the template flag.  I then installed the sample plugin.  I then went to the sample view for the sample plugin.  The form was there.  

I was unable to reproduce.

**Comment by greergan** [comment]
Sorry about this issue. I am not sure what was causing the initial problem but I was able to get it sorted.
